//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LadaAutoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продажи
    {
        public int Код_продажи { get; set; }
        public Nullable<int> Код_машины { get; set; }
        public Nullable<int> Клиент { get; set; }
        public Nullable<int> Код_менеджера { get; set; }
        public Nullable<int> Код_автосалона { get; set; }
    
        public virtual Автомобили Автомобили { get; set; }
        public virtual Автосалон Автосалон { get; set; }
        public virtual Клиенты Клиенты { get; set; }
        public virtual Менеджер Менеджер { get; set; }
    }
}
